module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Zircon',
    'Roaring',
    'Opal',
    'Boulder',
    'Silent',
    'Redwood',
    'Alexandrite',
    'Aquamarine',
    'Maple',
    'Misty',
    'Elk',
    'Emerald',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Pelham'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Creeks',
    'Shore',
    'Hollow',
    'Greater Gardens'
]